package com.dhcc.ms.plugin.datatype.preferences;

public interface PreferenceConstants {
	String DOWNLOADER_TYPE = "DOWNLOADER_TYPE";
	String MAVEN_DOWNLOADER_TYPE = "MAVEN";
	String URL_DOWNLOADER_TYPE = "URL";

	String MAVEN_DOWNLOADER_GROUPID = "MAVEN_DOWNLOADER_GROUPID";
	String MAVEN_DOWNLOADER_ARTIFACTID = "MAVEN_DOWNLOADER_ARTIFACTID";
	String MAVEN_DOWNLOADER_VERSION = "MAVEN_DOWNLOADER_VERSION";

	String URL_DOWNLOADER_PATH = "URL_DOWNLOADER_PATH";

	String JAVADOC_CHARSET = "JAVADOC_CHARSET";
	String ROOT_DATATYPE_PATH = "ROOT_DATATYPE_PATH";
}
